version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: employee_postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123  # Nur f√ºr lokale Entwicklung!
      - POSTGRES_DB=employeedb
    ports:
      - "5432:5432"  # leitet den Docker-Port 5432 auf den PC-Port 5432 um
    volumes:
      - postgres_data:/var/lib/postgresql/data # WICHTIG: Damit Daten beim Neustart erhalten bleiben!

volumes:
  postgres_data: